### ISSUE TITLE
Layer Information not being retrieved.

### ISSUE THREAD

**Issue by JoshuaRLi** [microscaling/microbadger#32] opened 2017-11-22 22:39 UTC
Relevant: #30 

Looks like layer information isn't being pulled. I've got two images [here](https://microbadger.com/images/joshuarli/alpine-python3-pip) and [here](https://microbadger.com/images/joshuarli/alpine-usanic) without it.

**Comment by IceflowRE** [comment] 2017-11-23 11:50
The last link seems to be fixed.
Here are another example: [image](https://microbadger.com/images/iceflower/redeclipse-server), they get mostly daily pushes.

**Comment by JoshuaRLi** [comment] 2017-11-23 15:23
Interesting. Guess I'll wait a bit more then.

**Comment by rossf7** [comment] 2017-11-23 19:05
Layer information has now been retrieved for all 3 of your images. This was caused by a big backlog in our inspection queue.

We'll see what we can do to prevent the backlog happening again.

**Comment by JoshuaRLi** [comment] 2017-11-23 21:54
@rossf7 Thanks! 👍

**Comment by bkimminich** [comment] 2017-12-13 11:10
Hi @rossf7! My image https://microbadger.com/images/bkimminich/juice-shop is also not giving any layer information for quite a while already. Is this another backlog issue, or is something in my multi-stage `Dockerfile` maybe causing the layer analysis to fail?

**Comment by rossf7** [comment] 2017-12-17 21:19
@bkimminich Your image is now fixed but it was affected by the backlog issue.

We're working on the backlog issue. In the meantime you can call the webhook URL and this will trigger your image to be re-inspected. This should fix the problem provided there isn't a backlog in the queue.

**Comment by tboerger** [comment] 2018-01-09 12:07
I would like to get the webhook url for https://microbadger.com/images/plugins/matrix and https://microbadger.com/images/plugins/manifest but they are still in processing :(

**Comment by lizrice** [comment] 2018-02-06 08:59
I think we have these images now, but if you still see issues please do re-open

**Closed by lizrice** 2018-02-06 08:59 UTC

**Comment by tboerger** [comment] 2019-01-25 09:36
You can always call the webhook to update.
