### ISSUE TITLE
Repo not found on Docker Hub

### ISSUE THREAD

**Issue by izonder** [microscaling/microbadger#19] opened 2017-02-13 13:25 UTC
Microbadger retrieved repos data from Docker when the certain repo was created but an image wasn't still pushed. And now I get an error "izonder/lanny not found on Docker Hub", but it exists.

**Comment by rossf7** [comment] 2017-02-15 12:59
Hi @izonder sorry we had a problem inspecting your image. I've re-inspected it and it's now on the site.

https://microbadger.com/images/izonder/lanny

**Comment by izonder** [comment] 2017-02-15 13:11
But you see, there is the same problem with another repo: https://microbadger.com/images/izonder/janny
And the problem is still existing... Why can't you re-inspect it automatically by request?

**Comment by rossf7** [comment] 2017-02-15 13:22
Hi @izonder I've reopened as I didn't realise it was affecting multiple images. We've seen this happen a few times but we haven't tracked down the cause.

I'll take another look probably tomorrow.

**Comment by rossf7** [comment] 2017-02-15 13:59
Quick update to say your izonder/janny image is also there. There are about 20 other images with the same problem.

The issue is the webhook URL wasn't generated successfully which we use to refresh the images. There is a possible fix to the refresh process that would help but we also need to find the cause.

I've run out of time to spend on this today but I'll try and take another look tomorrow.

**Comment by danshan** [comment] 2017-03-05 13:45
Same problem: 
https://microbadger.com/images/danshan/shanhh-jekyll
https://hub.docker.com/r/danshan/shanhh-jekyll/

**Comment by rossf7** [comment] 2017-03-05 14:56
@danshan We got a 404 from the Docker Hub Registry API the first time we inspected your image. Has this image always been public or has it been private at any point?

This 404 triggered a bug in MicroBadger. It meant we didn't generate the auth token we add to each webhook URL. We use the webhooks internally to refresh the metadata for each image.

For now I've manually resubmitted the 25 images affected. But this is an annoying bug we need to fix.

**Comment by danshan** [comment] 2017-03-06 07:50
@rossf7 thank you so much.
all my images are public from the beginning.

**Comment by danshan** [comment] 2017-03-10 05:48
https://hub.docker.com/r/danshan/prometheus-docker/
not found again
https://microbadger.com/images/danshan/prometheus-docker

**Comment by jpillora** [comment] 2017-03-16 08:17
Getting: *Layer information not yet retrieved*
https://microbadger.com/images/jpillora/cloud-torrent

Though it was working a few days ago

**Comment by xmjiao** [comment] 2017-03-24 12:48
I am having the similar issue with docker images "compdatasci/pandas-notebook" and "compdatasci/scipy-notebook".

**Comment by zeroc0d3** [comment] 2017-05-02 01:32
I got still "not found"
1) https://microbadger.com/images/zeroc0d3/ubuntu-ruby
2) https://microbadger.com/images/zeroc0d3/nginx-unicorn-rails

**Comment by klud1** [comment] 2017-05-26 15:10
is it working? i got "error" on every image i look for

**Comment by rossf7** [comment] 2017-05-26 16:32
@klud1 thanks for reporting this. We had downtime due to our RDS instance being out of storage. The site is back up now. We had problems with our monitoring and I didn't get alerted :( I'll get that fixed over the weekend.

Its a separate issue to these other images not being found. That is due to a bug with the way we fetch metadata from Docker Hub that affects a small number of images. It's very annoying so apologies if your images are affected.

**Comment by klud1** [comment] 2017-05-26 16:43
@rossf7 Oh, it sucks! No need to apologize, thanks for the great work you do!

**Comment by wisicn** [comment] 2017-07-10 15:38
I also get "not found"
 https://microbadger.com/images/wisicn/shootback-supervisor

please help to fix it. 

thanks

**Comment by JoshuaRLi** [comment] 2017-07-22 00:10
@rossf7 I'm having the same problem with [this](https://microbadger.com/images/joshuarli/alpine-usanic) image of mine.

What happened was I created an empty Docker repo linked to GitHub, signed up for MB, then built the Docker repo from GitHub.

Looks to me like fetching Docker Hub metadata is a one-time thing? I was hoping it would poll Docker Hub for reinspections. I'd appreciate it if you could reinspect mine and maybe add a manual "re-inspect" or "retry" button. I was going to try deleting my account then creating a new one to reimport Docker Hub metadata, but couldn't find out how to delete my account.

Thanks!

**Comment by rossf7** [comment] 2017-07-22 14:08
@JoshuaRLi @wisicn your images are both fixed.

You were both hit by the same bug. We use the webhook URL we generate for each image to refresh it once a day. In some cases if the image doesn't exist or the first API call to Docker Hub fails then we don't generate a webhook URL.

A fix is in progress but until then it needs to be fixed manually. We're no longer working on MicroBadger full time which is why this bug has been open for a while.

**Comment by JoshuaRLi** [comment] 2017-07-22 18:21
Okay, happy to know you guys are aware of the issue and thanks for the manual fix! :tada:

**Comment by rossf7** [comment] 2017-07-26 17:34
Closing, the bug fix is deployed and the manual fix has been made for existing images.  😄  🎉 

Please open a new issue if you still have problems.

**Closed by rossf7** 2017-07-26 17:34 UTC

**Comment by jemcgrath1** [comment] 2017-09-04 02:02
Issue appears to have occurred for my repo as well :(

Are you able to do a manual fix please?
https://microbadger.com/images/jemcgrath1/vpnrouter

**Comment by LKay** [comment] 2017-09-12 03:28
Problem still persists
https://microbadger.com/images/lkay/elasticmq

**Comment by lizrice** [comment] 2017-10-02 12:03
Both those last two images seem to be working OK btw.

**Comment by Rathorian** [comment] 2017-10-09 10:58
I have the same problem !

**Comment by rossf7** [comment] 2017-10-09 18:49
@Rathorian Looks like your plusxml image has now been inspected.

https://microbadger.com/images/rathorian/pluxml

At certain times we get a backlog in our inspection queue and it can take much longer than the 30 seconds we state on the inspection page. We'd love to reduce these delays but we're no longer working full time on microbadger so I can't give an ETA on that fix.

**Comment by Rathorian** [comment] 2017-10-09 19:12
Thank you, indeed, the image has been inspected

**Comment by Fish2** [comment] 2017-12-17 02:15
Hi 
All of my images seam broken as well

**Comment by cnrmck** [comment] 2018-06-06 14:52
Hi, my image doesn't seem to be working either:
https://microbadger.com/images/cnrm/rpi-raspbian-opencv2.4.13
https://hub.docker.com/r/cnrm/rpi-raspbian-opencv2.4.13/

**Comment by lizrice** [comment] 2018-06-06 15:22
hi @cnrmck, I've just manually refreshed it and the info is there now

**Comment by kelsey19** [comment] 2018-06-07 18:01
Hi, same issue here: https://microbadger.com/images/kelsey19/composeit

**Comment by lizrice** [comment] 2018-06-28 14:57
@kelsey19 yours is also ok now

**Comment by lyrahgames** [comment] 2018-08-02 07:54
I am sorry that I have to bother you, but I am experiencing the same issue with one of my images.

https://microbadger.com/images/lyrahgames/graphics-environment
https://github.com/lyrahgames/docker-graphics-environment

Thank you in advance!

**Comment by piotr-semenov** [comment] 2018-11-22 10:52
Dear microbadger development team,

I get "Layer information not yet retrieved" for https://microbadger.com/images/semenovp/tiny-elm/. Though it was working fine yesterday.

Thank you in advance!
