### ISSUE TITLE
Infinite processing meta

### ISSUE THREAD

**Issue by forumi0721** [microscaling/microbadger#33] opened 2017-12-01 07:28 UTC
hi
I use microbadger many repository.
But 1 repo cannot finish processing.

What's the wrong?

https://microbadger.com/images/forumi0721archx64build/arch-x64-dev-android

**Comment by rossf7** [comment] 2017-12-01 08:38
Hi,
your image has now been processed. 

We had a problem with the overnight refresh process that updates the image metadata. This meant new images were not being processed. Still investigating the cause of the overnight refresh problem but I'm going to close this.

Thanks for reporting the problem!

**Closed by rossf7** 2017-12-01 08:38 UTC

**Comment by dennybaa** [comment] 2018-12-07 11:43
Same issue and it is constantly reoccurring.  Why?

**Comment by dennybaa** [comment] 2018-12-07 11:51
This is always happens :((((
![](https://i.gyazo.com/1361417508287522f577bc8ca3e41900.png)

with one or another repo. Micro-badger does not work stable, what does these issues cause?
